Repository jenkinsci/next-executions-plugin, pull requests merged in 2023-11, with the labels that each got.

#55 Handle RareOrImpossibleDateException when evaluating crontabs
  src/main/java/hudson/plugins/nextexecutions/utils/NextExecutionsUtils.java
Labels: bug, hacktoberfest, hacktoberfest-accepted

#60 Use same style as other Jenkins widgets
  src/main/resources/hudson/plugins/nextexecutions/NextExecutionsComputerWidget/index.jelly
  src/main/resources/hudson/plugins/nextexecutions/NextExecutionsWidget/index.jelly
  src/main/resources/hudson/plugins/nextexecutions/ParametrizedNextExecutionsWidget/index.jelly
Labels: chore, ui, ux

#62 Ignore disabled workflow/pipeline jobs on widget and column
  src/main/java/hudson/plugins/nextexecutions/utils/NextExecutionsUtils.java
  src/main/java/hudson/plugins/nextexecutions/utils/ParameterizedNextExecutionsUtils.java
Labels: bug

#63 Ensure correct bom version when jenkins version updated
  updatecli/updatecli.d/update-jenkins-version.yml
Labels: chore
