Repository jenkinsci/next-executions-plugin, pull requests merged in 2024-01, with the labels that each got.

#79 Remove displayMode setting (fixes #78)
  README.adoc
  src/main/java/hudson/plugins/nextexecutions/NextBuilds.java
  src/main/java/hudson/plugins/nextexecutions/NextExecutionsWidget.java
  src/main/resources/hudson/plugins/nextexecutions/NextBuilds/global.jelly
  src/main/resources/hudson/plugins/nextexecutions/NextExecutionsWidget/index.jelly
  src/main/webapp/displayMode.html
Labels: bug, breaking

#80 Use Jenkinsfile from archetypes
  Jenkinsfile
Labels: chore

#88 Unit tests added for NextExecutionsUtils
  pom.xml
  src/test/java/hudson/plugins/nextexecutions/utils/NextExecutionsUtilsTest.java
Labels: tests
