Repository jenkinsci/next-executions-plugin, pull requests merged in 2024-03, with the labels that each got.

#97 Display message when not next execution is found to avoid empty widget
  src/main/java/hudson/plugins/nextexecutions/NextExecutionsComputerWidget.java
  src/main/java/hudson/plugins/nextexecutions/NextExecutionsWidget.java
  src/main/resources/hudson/plugins/nextexecutions/Messages.properties
  src/main/resources/hudson/plugins/nextexecutions/NextExecutionsComputerWidget/index.jelly
  src/main/resources/hudson/plugins/nextexecutions/NextExecutionsWidget/index.jelly
  src/main/resources/hudson/plugins/nextexecutions/ParametrizedNextExecutionsWidget/index.jelly
Labels: enhancement

#103 Add tests to improve test coverage
  src/main/resources/hudson/plugins/nextexecutions/Messages.properties
  src/test/java/hudson/plugins/nextexecutions/NextBuildsTest.java
  src/test/java/hudson/plugins/nextexecutions/NextExecutionsComputerWidgetTest.java
  src/test/java/hudson/plugins/nextexecutions/NextExecutionsWidgetTest.java
  src/test/java/hudson/plugins/nextexecutions/ParameterizedNextExecutionsWidgetTest.java
  src/test/java/hudson/plugins/nextexecutions/PossibleNextExecutionsWidgetTest.java
Labels: tests

#107 Set consistent timezone in Calendar.getInstance()
  src/test/java/hudson/plugins/nextexecutions/NextBuildsTest.java
Labels: tests

#109 Implementing a wordwrap so that longer job names will be rendered correct
  src/main/resources/hudson/plugins/nextexecutions/NextExecutionsWidget/index.jelly
Labels: bug
